apiVersion: v1
kind: Secret
metadata:
  name: invesa-secrets
  namespace: invesa
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:password@invesa-db:5432/invesa"
  JWT_ACCESS_SECRET: "changeme-access-secret"
  JWT_REFRESH_SECRET: "changeme-refresh-secret"
  POSTGRES_PASSWORD: "password"
